@startuml
skinparam BackgroundColor F0F0F0

participant "Worker Bluetooth" as workbt
participant "Service Bluetooth" as srvbt
participant "Database Agent" as sett
participant "Application Settings" as appsett

activate appsett
appsett -> sett : register cb on bonded devices change
    activate sett
appsett <- sett : bonded devices callback
    deactivate sett
        ... ...

appsett->srvbt : forget device msg(address)
    activate srvbt
    srvbt -> workbt : command(unpair, address)
        deactivate srvbt
        activate workbt


        workbt -> sett : update bonded devices
        deactivate workbt
            activate sett
appsett <- sett : bonded devices callback
            deactivate sett

@enduml
