@startuml
skinparam BackgroundColor F0F0F0
(*) --> If "Ramp target reached?" then
    If "New target differs by \nhysteresis value from \nthe old one?" then
    -> [Yes] "update ramp" as ur
    else
    ---> [No] "RampValue = \nRampTarget"
    Endif
else
--> [No] ur
Endif
@enduml
