option(ENABLE_APP_ALARM_CLOCK "Enable application alarm-clock" ON)
option(ENABLE_APP_CALCULATOR "Enable application calculator" ON)
option(ENABLE_APP_CALENDAR "Enable application calendar" ON)
option(ENABLE_APP_CALL "Enable application call" ON)
option(ENABLE_APP_CALLLOG "Enable application callog" ON)
option(ENABLE_APP_CLOCK "Enable application clock" ON)
option(ENABLE_APP_DESKTOP "Enable application desktop" ON)
option(ENABLE_APP_MEDITATION "Enable application meditation" ON)
option(ENABLE_APP_MESSAGES "Enable application messages" ON)
option(ENABLE_APP_MUSIC_PLAYER "Enable application music player" ON)
option(ENABLE_APP_NOTES "Enable application notes" ON)
option(ENABLE_APP_ONBOARDING "Enable application onboarding" ON)
option(ENABLE_APP_PHONEBOOK "Enable application phonebook" ON)
option(ENABLE_APP_NOTES "Enable application notes" ON)
option(ENABLE_APP_ONBOARDING "Enable application onboarding" ON)
option(ENABLE_APP_SETTINGS "Enable application settings" ON)
option(ENABLE_APP_SPECIAL_INPUT "Enable application special-input" ON)
