set(ENABLE_APP_ALARM_CLOCK ON CACHE INTERNAL "Enable application alarm-clock")
set(ENABLE_APP_CALCULATOR ON CACHE INTERNAL "Enable application calculator")
set(ENABLE_APP_CALENDAR ON CACHE INTERNAL "Enable application calendar")
set(ENABLE_APP_CALL ON CACHE INTERNAL "Enable application call")
set(ENABLE_APP_CALLLOG ON CACHE INTERNAL "Enable application callog")
set(ENABLE_APP_CLOCK ON CACHE INTERNAL "Enable application clock")
set(ENABLE_APP_DESKTOP ON CACHE INTERNAL "Enable application desktop")
set(ENABLE_APP_MEDITATION ON CACHE INTERNAL "Enable application meditation")
set(ENABLE_APP_MESSAGES ON CACHE INTERNAL "Enable application messages")
set(ENABLE_APP_MUSIC_PLAYER ON CACHE INTERNAL "Enable application music player")
set(ENABLE_APP_NOTES ON CACHE INTERNAL "Enable application notes")
set(ENABLE_APP_ONBOARDING ON CACHE INTERNAL "Enable application onboarding")
set(ENABLE_APP_PHONEBOOK ON CACHE INTERNAL "Enable application phonebook")
set(ENABLE_APP_SETTINGS ON CACHE INTERNAL "Enable application settings")
set(ENABLE_APP_SPECIAL_INPUT ON CACHE INTERNAL "Enable application special-input")
