@startuml
skinparam BackgroundColor F0F0F0

PowerManager -> CpuGovernor : GetMinimumFrequencyRequested
CpuGovernor --> PowerManager : minimumFrequency

...CPU frequency change...

PowerManager -> CpuGovernor : CpuFrequencyHasChanged

CpuGovernor -> cellularSentinel : CpuFrequencyHasChanged

CpuGovernor -> eInkSentinel : CpuFrequencyHasChanged
eInkSentinel -> DriverPWM : updatePWM
note right
Critical section!
mutex necessary
end note

@enduml
