@startuml
skinparam BackgroundColor F0F0F0

[Service DB] as srvcdb
[Service Bluetooth] as srvcbt
[Application Settings] as appstngs


srvcdb <-r-> srvcbt : SettingsAgent
srvcbt <-r-> appstngs : BluetoothMessages

@enduml
