FROM ubuntu:focal

MAINTAINER radoslaw.wicik@mudiata.com
# docker runner for PurePhone builds

RUN ln -fs /usr/share/zoneinfo/Europe/Warsaw /etc/localtime && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get full-upgrade -y && \
    apt-get install -y \
        ca-certificates \
        curl \
        gnupg2 \
        binutils \
        wget \
        git \
        make \
        pkg-config \
        gtkmm-3.0 \
        gcc-9 \
        g++-9 \
        portaudio19-dev \
        build-essential \
        vim \
        bash-completion \
        clang-format-10 \
        apt-utils \
        locales \
        tzdata \
        ninja-build \
        graphviz \
        doxygen \
        ccache && \
    ln -fs /usr/bin/python3 /usr/bin/python && \
    locale-gen pl_PL.UTF-8 \
               en_US.UTF-8 \
               de_DE.UTF-8 \
               es_ES.UTF-8 && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    mkdir -p /home/runner/app/settings

# ARM compiler
ADD assets/@ARM_GCC_PKG@ /usr/local/

# CMake
ADD assets/@CMAKE_PKG@ /usr/local/

ADD assets/@GH_RUNNER_PKG@ /home/runner/app

ENV CMAKE_NAME="/usr/local/@CMAKE_NAME@"
ENV ARM_GCC="/usr/local/@ARM_GCC@"

ENV PATH="/user/local/actions-runner:/usr/local/@CMAKE_NAME@/bin:/usr/local/@ARM_GCC@/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV TERM="xterm-256color"

COPY assets/cmd.sh /cmd.sh
RUN chmod +x /cmd.sh && \
    groupadd -r runner && \
    useradd --no-log-init -r -g runner runner && \
    chown -R runner:runner /home/runner

WORKDIR /home/runner/app

USER runner

ENTRYPOINT ["/cmd.sh"]





