version: '3'
services:
 gh-runner0:
   image: wearemudita/mudita_os_builder:1.6
   environment:
     WORKER_NAME: PureBuilder0
   env_file:
     - runner_settings
   entrypoint: /cmd.sh
 gh-runner1:
   image: wearemudita/mudita_os_builder:1.6
   environment:
     WORKER_NAME: PureBuilder1
   env_file:
     - runner_settings
   entrypoint: /cmd.sh
 gh-runner2:
   image: wearemudita/mudita_os_builder:1.6
   environment:
     WORKER_NAME: PureBuilder2
   env_file:
     - runner_settings
   entrypoint: /cmd.sh
