@startuml
skinparam BackgroundColor F0F0F0

actor User
participant ServiceBluetooth
==Start scan==
activate ServiceBluetooth
User -> ServiceBluetooth : BluetoothMessage(BluetoothMessage::Request::Scan)
ServiceBluetooth -> User : for each device: BluetoothScanResultMessage
deactivate ServiceBluetooth
==Stop scan==
User -> ServiceBluetooth : BluetoothMessage(BluetoothMessage::Request::StopScan)

@enduml
