#!/bin/bash

function printVar(){
    echo "$1: '${!1}'"
}

function getArmCC() {
    #download file to current directory
    wget --no-verbose --show-progress -O ${ARM_GCC_PKG} ${ARM_GCC_SOURCE_LINK}
}

function getCMake() {
    wget --no-verbose --show-progress -O ${CMAKE_PKG} ${CMAKE_SOURCE_LINK}
}

function getGHRunner() {
    wget --no-verbose --show-progress -O ${GH_RUNNER_PKG} ${GH_RUNNER_LINK}
}
