set(PROJECT_CONFIG_DEFINITIONS

        LOG_USE_COLOR=0
        LOG_REDIRECT=2
        SYSTEM_VIEW_ENABLED
        PROJECT_CONFIG_USER_DYNMEM_SIZE=10*1024*1024
        MODULE_CORE_CUSTOM_BUS

        CACHE INTERNAL ""
        )

message(STATUS "BlueKitchen selected")
set(BT_STACK "BlueKitchen")
