set(PROJECT_CONFIG_DEFINITIONS

        LOG_USE_COLOR=0
        LOG_REDIRECT=2
        SYSTEM_VIEW_ENABLED
        PROJECT_CONFIG_USER_DYNMEM_SIZE=10*1024*1024
        MODULE_CORE_CUSTOM_BUS

        CACHE INTERNAL ""
        )

message(STATUS "BlueKitchen selected")
set(BT_STACK "BlueKitchen")

#Remove SYSTEM_VIEW for Linux Target
if((${PROJECT_TARGET} STREQUAL "TARGET_Linux") AND (PROJECT_CONFIG_DEFINITIONS ${SYSTEM_VIEW_ENABLED}))
    string(REPLACE "SYSTEM_VIEW_ENABLED" "" PROJECT_CONFIG_DEFINITIONS "${PROJECT_CONFIG_DEFINITIONS}")
endif()

