set(BOARD_SOURCES ${BOARD_SOURCES}
        CACHE INTERNAL ""
        )

set(BOARD_DIR_INCLUDES ${BOARD_DIR_INCLUDES}

        ${CMAKE_CURRENT_SOURCE_DIR}/board/cross

        CACHE INTERNAL "")

set(BOARD_SOURCE_FILES_PROPERTIES ${BOARD_SOURCE_FILES_PROPERTIES}

        CACHE INTERNAL "")