set(BOARD_SOURCES ${BOARD_SOURCES}

		"${CMAKE_CURRENT_SOURCE_DIR}/board/rt1051/drivers/RT1051DriverI2C.cpp"
        "${CMAKE_CURRENT_SOURCE_DIR}/board/rt1051/fsl_drivers/fsl_lpi2c.c"
		"${CMAKE_CURRENT_SOURCE_DIR}/board/rt1051/fsl_drivers/fsl_clock.c"

        CACHE INTERNAL ""
        )

set(BOARD_DIR_INCLUDES ${BOARD_DIR_INCLUDES}

        CACHE INTERNAL "")


set(BOARD_SOURCE_FILES_PROPERTIES ${BOARD_SOURCE_FILES_PROPERTIES}

        CACHE INTERNAL "")

