@startuml
(*) --> [initialization] "measurement" as meas
"teperature range\n violation interrupt" -> meas
If "Detected range" then
    --> [T = 1~45 Cdeg] charger On
    --> set normal\ninterrupt bounds
    else
    ---> [T<=0 Cdeg] "charger off" as co
    --> set interrupt\nbounds with 1Cdeg hysteresis
    else
    --> [T>45 Cdeg] co
Endif
@enduml

