@startuml
skinparam BackgroundColor F0F0F0

participant "Battery level check" as batt
participant "System Manager" as sysmgr
participant "Service Cellular" as cell
participant "Application Manager" as appmgr
participant "ApplicaionDesktop" as appdsktp

== Initial check ==

    activate cell
    cell -> sysmgr : CellularCheckIfStartAllowedMessage
    activate sysmgr
    sysmgr -> cell : CellularPowerStateChange(Off)
    cell -> cell : handle_power_state_change
    sysmgr -> appmgr : CriticalBatteryLevelNotification(true)
    deactivate cell
    deactivate sysmgr
    activate appmgr
    appmgr -> appdsktp : actions::DisplayLowBatteryNotification
    deactivate appmgr
alt
    activate cell
    cell -> sysmgr : CellularCheckIfStartAllowedMessage
    activate sysmgr
    sysmgr -> cell : CellularPowerStateChange(On)
    cell -> cell : handle_power_state_change
    sysmgr -> appmgr : CriticalBatteryLevelNotification(false)
    deactivate cell
    deactivate sysmgr
end

== Normal flow ==
    batt -> sysmgr : BatteryStateChangeMessage
    activate sysmgr
    sysmgr -> cell : CellularPowerStateChange(Off)
    activate cell
    cell -> cell : handle_power_state_change
    sysmgr -> appmgr : CriticalBatteryLevelNotification(true)
    deactivate cell
    activate appmgr
    appmgr -> appdsktp : actions::DisplayLowBatteryNotification
    deactivate appmgr
alt
    batt -> sysmgr : BatteryStateChangeMessage
    activate sysmgr
    sysmgr -> cell : CellularPowerStateChange(On)
    activate cell
    cell -> cell : handle_power_state_change
    sysmgr -> appmgr : CriticalBatteryLevelNotification(false)
    deactivate cell
end

@enduml
