name: 'PR Tasks Completed Check'
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review, unlocked]

jobs:
  task-check:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
